test:
  adapter: postgresql
  encoding: utf8
  database: onebitbot_test
  pool: 5
  username: postgres
  host: postgres

development:
  adapter: postgresql
  encoding: utf8
  database: onebitbot_development
  pool: 5
  username: postgres
  host: postgres